### PR TITLE
Saku02 (Last Part)

### PR DESCRIPTION
**Pull request by silverwolf-waltz**
Real life, more translation adjustments than usual, and flagging motivation caused it to take a bit, but we're done!

Would you be fine with a contributor list one/few liner in the readme? It's not a big deal, but it came to mind the other day since I run into it on GitHub occasionally.

Note that after you merge this in, I have a few small build system improvements/suggestions I'll be pull requesting.

### CODE REVIEW

**Comment by ooa113y** [comment]
Thanks so much!

> Would you be fine with a contributor list one/few liner in the readme?
Absolutely. GitHub already kind of provides this (there's a "Contributors" link on the right sidebar, and *that* doesn't require me to manually update anything), but I can certainly link that same thing from the readme just the same.

> Note that after you merge this in, I have a few small build system improvements/suggestions I'll be pull requesting.
Considering this merge marks the end of the project, I'm not all that sure there's a point in improving minor things like that anymore, but I suppose I don't mind that if it helps translation forks and the like.

I wanted to ask: have you built/tested your changes yourself? I unfortunately do not have hardware powerful enough to run a Swich emulator anymore as I have lost access to my desktop PC, so I'd like to know if I can announce this project as "ready" or if I should wait for some testing to be done first. If you can't/don't want to do that, I do have someone in mind who can, so don't worry too much about it.

**Comment by silverwolf-waltz** [comment]
> Absolutely. GitHub already kind of provides this (there's a "Contributors" link on the right sidebar, and that doesn't require me to manually update anything), but I can certainly link that same thing from the readme just the same.

Please do if you're fine with that. I did notice the contributors on the sidebar, but it's easy to miss, especially on mobile where it's at the very end (I always read to the very end myself... sometimes 😅)

> Considering this merge marks the end of the project, I'm not all that sure there's a point in improving minor things like that anymore, but I suppose I don't mind that if it helps translation forks and the like.

Yeah, I'm just considering it final project cleanup, as it'll help with reproducibility, any new proofreaders, and any translation forks.

I wanted to ask: have you built/tested your changes yourself? I unfortunately do not have hardware powerful enough to run a Swich emulator anymore as I have lost access to my desktop PC, so I'd like to know if I can announce this project as "ready" or if I should wait for some testing to be done first. If you can't/don't want to do that, I do have someone in mind who can, so don't worry too much about it.

I have built it, and have a system that can emulate it. I will likely play through it in the next day or two to enjoy it, as I generally work on it without playing through at all until the very end. I also know someone who has reallllly been waiting for me to finish it, so you'll have a second data point really soon 😆

**Comment by ooa113y** [comment]
I'm just curious to know if it crashes at any point, typos and the like are a minor issue that I can certainly fix later. If it's not too much to ask, could you boot the game up, load the story and just press the R button to skip to the very end? You may need to turn "skip unread text" on in the settings first.

**Comment by silverwolf-waltz** [comment]
All done. It made it through to the end without crashing 🎉

**Comment by ooa113y** [comment]
Thanks a bunch! Merging/releasing now.

**Pull request merged**
